Trip calculator step 2
Cenivell/Python pull request #3
Opened 2023-07-06 11:42 UTC by Cenivell

Part 2

2023-07-10 08:13 UTC, Seredyak1 requested changes
Найперше - тобі треба подумати як зробити код бліьш структурованим і читабельним - бо зараз просто накидано коментарі / якісь частини коду. 
Спробуй розбити рядочком свій код на логічні частини, і власне для цих частин додай коментарі як пояснення загальної логічки, а не детальної.

2023-07-10 08:28 UTC, Seredyak1 commented on trip_calculator.py
> +#Щоб не робити повторювальну дії вивожу в змінну
От власне про такий комент я мав на увазі у залаьному коментарі.

2023-07-10 08:28 UTC, Seredyak1 commented on trip_calculator.py
> +food_weight_list=[100,57,100,40,150]
ця частина взагалі неконткретна, і виглядає як просто набір чисел.
подумай як краще було б зорганізувати назву і ці параметри продукту в інший спосіб.

2023-07-10 08:28 UTC, Seredyak1 commented on trip_calculator.py
> +                print('Amount of', key, int(value))
тут завеликий відступ

2023-07-10 08:28 UTC, Seredyak1 commented on trip_calculator.py
> +def print_output_in_console(dictionary: dict):
власне, сам етод лежить просто посеред коду, так не робиться)
це до цього коментаря про структуризацію, подумай як то краще зорганізувати

2023-07-10 08:28 UTC, Seredyak1 commented on trip_calculator.py
> +while x<duration_days:
така умова загубить загубить один день

2023-07-10 08:28 UTC, Seredyak1 commented on trip_calculator.py
> +trip_food_variation_2_dict = {
трохи дивне формування словника - ти б міг порахувати це і без якогосьсловника чи додаткових дій. 
подумай, чи зручно би було таким його підтримуватися і змінювти, якщо ти хочеш додати кілька нових продуктів

2023-07-10 11:18 UTC, Cenivell commented on trip_calculator.py
> +while x<duration_days:
Не загубить
![image](https://github.com/Cenivell/Python/assets/137086607/b2f8c756-cc65-41e4-9b58-c59ef74d4db1)

2023-07-10 11:19 UTC, Cenivell commented on trip_calculator.py
> +trip_food_variation_2_dict = {
Не розумію в чому проблема. Потрібно зробити все в один словник?

2023-07-10 11:19 UTC, Cenivell commented on trip_calculator.py
> +#Щоб не робити повторювальну дії вивожу в змінну
Виправив

2023-07-10 11:19 UTC, Cenivell commented on trip_calculator.py
> +                print('Amount of', key, int(value))
Виправив

2023-07-10 11:19 UTC, Cenivell commented on trip_calculator.py
> +def print_output_in_console(dictionary: dict):
Виправив

2023-07-10 11:21 UTC, Cenivell commented on trip_calculator.py
> +food_weight_list=[100,57,100,40,150]
Так підійде?

2023-07-10 11:56 UTC, Seredyak1 commented on trip_calculator.py
> +food_weight_dict_var_1={
Так краще, би виглядає вже зрозуміло, що до чого і як відноситься.
Але тепер маєщ по суті нову проблему - в тебе два одакові словника з однаковими ключами, але різними значеннями)

2023-07-10 11:56 UTC, Seredyak1 commented on trip_calculator.py
> +    total_food_weight+=sum(food_weight_dict_var_1.values())*num_of_participation
У цьому циклі у тебе також виникає повторювальна дія.

2023-07-10 11:56 UTC, Seredyak1 commented on trip_calculator.py
> +food_weight_list=[100,57,100,40,150]
Так краще, але там звлишив новий коментар

2023-07-10 11:56 UTC, Seredyak1 commented on trip_calculator.py
> +trip_food_variation_2_dict = {
Можливо, бо в тут ти просто розраховуєш кількість порцій на кількість осіб.
але це ж саме ти можеш зробити іншою дією.

При переорагнізації подумай, що значенням елемента словник аможе бути не тільки число чи стрінга, але й інші типи даних.

2023-07-10 11:56 UTC, Seredyak1 commented on trip_calculator.py
> +#Виписую вагу
Однією з умов виковння має бути повний список продуктів та їх кількість.
Тут як я бачу виходять просто повторювальні списки, а треаб якраз узагальнене число.

2023-07-13 08:14 UTC, Cenivell commented on trip_calculator.py
> +#Виписую вагу
Зробив.

2023-07-13 08:15 UTC, Cenivell commented on trip_calculator.py
> +food_weight_dict_var_1={
Виправив.

2023-07-13 08:15 UTC, Cenivell commented on trip_calculator.py
> +trip_food_variation_2_dict = {
Так підійде?

2023-07-18 12:29 UTC, Seredyak1 commented on trip_calculator.py
> +    for item in dictionary.values():
sum() - гарний метод, що ти виокристовував перед цим.

2023-07-18 12:29 UTC, Seredyak1 commented on trip_calculator.py
> +        dictionary[key]['amount'] += dictionary[key]['number_per_person_per_day']*x
це ок, що метод нічого не вертає?

2023-07-18 12:29 UTC, Seredyak1 commented on trip_calculator.py
> +if duration_days >= 1:
Спробуй сформувати загальний список продуктів, куди по чуті має увійти тільки назвв продукту - його кількість (ну і можна одиницю виміру додати щоб легше читалося)

2023-07-20 10:45 UTC, Cenivell commented on trip_calculator.py
> +        dictionary[key]['amount'] += dictionary[key]['number_per_person_per_day']*x
Виправив

2023-07-20 10:46 UTC, Cenivell commented on trip_calculator.py
> +if duration_days >= 1:
Не розумію що потрібно зробити

2023-07-20 11:12 UTC, Seredyak1 commented on trip_calculator.py
> +if duration_days >= 1:
загальниний ліст з усіма елементами продуктів.
тобто має бути не так принт елементів - а саме масив продуктів.

2023-07-24 07:24 UTC, Seredyak1 requested changes

2023-07-24 07:24 UTC, Seredyak1 commented on trip_calculator.py
> +    for dictionary in [current_dict]:
трохи не зрозумілий крок, бо:

1) якщо у тебе аргумент функції завжди один, і це словник - то і звертайся до нього напряму, типу 
for key in current_dict.keys()

2) якщо там моде бути  декліька словників, то відповідно і метод, і анотація вже має приймати ліст, і тобі не треба запизувати словник ще у ліст.

2023-07-24 07:24 UTC, Seredyak1 commented on trip_calculator.py
> +x = 0; y = 0
що таке x? що таке y?
назви змінні відповдіно)

2023-07-24 07:24 UTC, Seredyak1 commented on trip_calculator.py
> +def add_amount_to_food_dictionary(current_dict: dict, x: dict) -> dict:
якщо х == out_dict, то аргемент методу можна так і назвати

2023-07-24 07:24 UTC, Seredyak1 commented on trip_calculator.py
> +    total_food_weight += sum(item.get('weight', 0) for item in globals()[prefix + str(y) + suffix].values())
можливо, це було б зручніше зробити однією дією, коли буде готовий out_dict, і порахувати всі його значення?

2023-07-25 10:27 UTC, Cenivell commented on trip_calculator.py
> +    total_food_weight += sum(item.get('weight', 0) for item in globals()[prefix + str(y) + suffix].values())
Але ж в out_dict я записую тільки назву та кількість. Все ж таки зробити щоб в out_dict записувались всі данні?

2023-07-26 15:15 UTC, Seredyak1 approved these changes

2023-07-26 15:18 UTC, merged