Task 3
Cenivell/Python pull request #4
Opened 2023-07-31 09:14 UTC by Cenivell

Task 3

2023-07-31 09:36 UTC, Seredyak1 requested changes

2023-07-31 09:36 UTC, Seredyak1 commented on trip_calculator.py
> +    trip_kilometers_per_day[str(duration_days)] = distance_travelled
Ключ дікта може бути стрінгою, тому не обов'язково переводити у стрінгу.

2023-07-31 09:36 UTC, Seredyak1 commented on trip_calculator.py
> +while trip_distance > 0:
з точки зору групації коду. можливо це варто винести у окремий метод.

2023-07-31 09:36 UTC, Seredyak1 commented on trip_calculator.py
> +    total_food_weight -= sum(item.get('weight', 0)\
можливо це варто зробити теж методом?

2023-07-31 09:36 UTC, Seredyak1 commented on trip_calculator.py
> +    remove_amount_from_food_dictionary(globals()[prefix + str(variation_num) + suffix], out_dict)
От влесне хороший приклад по globals()
якщоу  тебе зміна глобальна, то ти її не маєш передавати як аргумент методу. бо вона має йому бути доступна.
може варто хробити її тоді не глобально. а просто скласти у структурі і нічого глобально не писати?

2023-07-31 09:36 UTC, Seredyak1 commented on trip_calculator.py
> +    print("Distance travelled on day "+str(current_days)+" is",trip_kilometers_per_day[str(current_days)],"kilometers")
зроби це краще через форматування стрічки, бо так не моливо вичитати що ти там хочеш

2023-08-02 05:45 UTC, Cenivell commented on trip_calculator.py
> +    remove_amount_from_food_dictionary(globals()[prefix + str(variation_num) + suffix], out_dict)
Але мені може потрібно бути використати цей метод знову. А якщо навіть в аргументі забрати глобал то воно не працює.

2023-08-22 13:12 UTC, merged